### ISSUE TITLE
Enable restart-policy on docker images

### ISSUE THREAD

**Issue by jpsenior** [Apstra/aosom-streaming#9]
When rebooting the aosom-streaming server, I have to re-start the daemons manually.

Please modify the init/start scripts to use --restart always or --restart unless-stopped policies for the containers. This will allow them to start with the docker daemon as it starts.

**Comment by jeremyschulman** [comment]
@jpsenior - your request is outside the scope of this project; given that this project is simply the docker images and the related "make" file to manage the admin functions; i.e. wraps around docker-compose and some curl commands.

That said, I would suggest you consider installing this system onto the AOS server directly.  Then you can modify the AOS server docker-compose file so that it restarts these containers.  Both @dgarros and I have experimented with running aosom-streaming containers on the AOS server and have seen this work A-OK for POC/lab purposes.

closing this issue.

**Comment by dgarros** [comment]
@jpsenior , if you want to give it a try there is one things to keep in mind. 
Currently the Telegraf input plugin assume that AOS is already running, if the connection to AOS fails the container will continue to run but it will not pull additional information from AOS (devices role, blueprint names etc ...)
